// generated by cbindgen. do not edit.

typedef struct udpsocket_error udpsocket_error;

void udpsocket_error_drop(struct udpsocket_error *err);

size_t udpsocket_error_print(const struct udpsocket_error *err, uint8_t *buf, size_t buf_len);

struct udpsocket_error *udpsocket_bind(const char *addr, void **socket_out);

void udpsocket_drop(void *socket);

struct udpsocket_error *udpsocket_set_nonblocking(void *socket, bool nonblocking);

struct udpsocket_error *udpsocket_connect(void *socket, const char *addr);

/**
 * The send method of a connected UdpSocket does not guarantee delivery of packets, as UDP is
 * inherently an unreliable protocol. If the server is not up or reachable, the send method may
 * not fail immediately. Instead, it can return successfully, indicating that the data has been
 * sent to the kernel's socket buffer, even if it is not actually delivered to the server.
 */
struct udpsocket_error *udpsocket_send(void *socket,
                                       const uint8_t *buf,
                                       size_t buf_len,
                                       size_t *n_out);

struct udpsocket_error *udpsocket_recv(void *socket, uint8_t *buf, size_t buf_len, size_t *n_out);
