use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(cbindgen::Config {
            language: cbindgen::Language::C,
            usize_is_size_t: true,
            no_includes: true,
            header: Some("// generated by cbindgen. do not edit.".to_string()),
            ..Default::default()
        })
        .generate()
        .expect("could not generate bindings")
        .write_to_file("bindings.h");
}
